### ISSUE TITLE
Wireless health endpoints

### ISSUE THREAD

**Issue by Chris911** [zebbra-repos/node-meraki#6]
Hi,

Any plans to integrate the [wireless health](https://dashboard.meraki.com/api_docs#wireless-health) endpoints? It's the only missing piece that prevents us from using your lib :)

**Comment by mbaertschi** [comment]
Hi @Chris911 

Sorry for the late response. I added the `raw requests` features a while ago but left them undocumented. You can make use of them to call any meraki ressource while using the wrapper features of this library. Please have a look at the docs for more information.
